--EJER 1
create or replace PROCEDURE EXAMEN_31 (PNUM_SURTIDOR NUMBER, PCANTIDAD NUMBER, PPRECIO NUMBER)
AS
NULOS EXCEPTION;
ENTRE_SURTIDOR EXCEPTION;
ENTRE_CANTIDAD EXCEPTION;
ENTRE_PPRECIO EXCEPTION;
NUM_ESCRITO VARCHAR2 (32676);
PTOTAL NUMBER;
BEGIN 
IF (PNUM_SURTIDOR IS NULL) OR (PCANTIDAD IS NULL) OR (PPRECIO IS NULL) OR (PNUM_SURTIDOR<0) OR (PCANTIDAD<0) OR (PPRECIO<0)THEN
  RAISE NULOS;
END IF;
IF PNUM_SURTIDOR NOT BETWEEN 1 AND 4 THEN
  RAISE ENTRE_SURTIDOR;
END IF;
IF PCANTIDAD NOT BETWEEN 1 AND 80 THEN
  RAISE ENTRE_CANTIDAD;
END IF;
IF PPRECIO<=0 THEN
  RAISE ENTRE_PPRECIO;
END IF;

IF PNUM_SURTIDOR = 1 THEN
  NUM_ESCRITO:='UNO';
END IF;

IF PNUM_SURTIDOR = 2 THEN
  NUM_ESCRITO:='DOS';
END IF;

IF PNUM_SURTIDOR = 3 THEN
  NUM_ESCRITO:='TRES';
END IF;

IF PNUM_SURTIDOR = 4 THEN
  NUM_ESCRITO:='CUATRO';
END IF;

  VER('HA REPOSTADO GASOLIDA EN EL SURTIDOR '||NUM_ESCRITO);
  PTOTAL:=ROUND((PCANTIDAD*PPRECIO),2);
  VER('EL TOTAL ES '||PTOTAL||'Ç');
  VER('TIENE UN DESCUENTO DE '||CALCULA_DESCUENTO(PTOTAL)||' Ç PARA SU PROXIMA VISITA');
  
EXCEPTION
  WHEN NULOS THEN
    VER('ERROR DATOS INTRODUCIDOS NULOS');
  WHEN ENTRE_SURTIDOR THEN
    VER('ERROR PNUM_SURTIDOR NO ESTA ENTRE 1 Y 4');
  WHEN ENTRE_CANTIDAD THEN
    VER('ERROR PCANTIDAD NO ESTA ENTRE 1 Y 80');
  WHEN ENTRE_PPRECIO THEN
    VER('ERROR PPRECIO ES 0 O MENOR');
  
END;

EXECUTE EXAMEN_31(3,20,1.89);

CREATE OR REPLACE FUNCTION CALCULA_DESCUENTO (TOTAL NUMBER)
RETURN NUMBER
IS
DESCUENTO NUMBER;
BEGIN
  DESCUENTO:= ROUND((TOTAL*(2/100)),2);
  RETURN DESCUENTO;
END;



--EJER2

EXECUTE PROBANDO('06/04/2022');

CREATE OR REPLACE PROCEDURE PROBANDO(PFECHA DATE)
AS
BEGIN
  VER(EXAMEN_32(PFECHA));
END;

CREATE OR REPLACE FUNCTION EXAMEN_32 (FECHA DATE)
RETURN DATE
IS
  VFECHA DATE;
BEGIN
  VFECHA:=FECHA+1;
  LOOP
    IF TO_CHAR(VFECHA,'D')=6 THEN
      RETURN(VFECHA);
    END IF;
      VFECHA:=VFECHA+1;
  END LOOP;
END;

--EJER3
CREATE OR REPLACE FUNCTION EXAMEN_33 (PCADENA VARCHAR2)
RETURN NUMBER
IS
VOCALES NUMBER:=0;
BEGIN 
  FOR I IN 1..LENGTH(PCADENA) LOOP
    IF SUBSTR(PCADENA,I,1) NOT BETWEEN 'a' AND 'z' THEN 
       VOCALES:=-1;
       EXIT;
    END IF;
    IF SUBSTR(PCADENA,I,1) IN ('A','a','e','E','i','I','o','O','u','U') THEN 
       VOCALES:=VOCALES+1;
    END IF;
  END LOOP;
  RETURN VOCALES;
END;
--EJER4
CREATE OR REPLACE PROCEDURE COSAS(CAD1 VARCHAR2, CAD2 VARCHAR2)
AS
PRIMERO NUMBER;
SEGUNDO NUMBER;
NEGATIVO EXCEPTION;
BEGIN
  PRIMERO:=EXAMEN_33(CAD1);
  SEGUNDO:=EXAMEN_33(CAD2);
  
  IF PRIMERO=-1 OR SEGUNDO=-1 THEN
  RAISE NEGATIVO;
  END IF;
  
  IF PRIMERO>SEGUNDO THEN
    VER(CAD1);
  ELSE
    VER(CAD2);
  END IF;
  
  EXCEPTION
    WHEN NEGATIVO THEN
      VER('ERROR CON CADENAS RECIBIDAS');
  
END;

EXECUTE EXAMEN_34('PATATA','VACACIONES');

