CREATE OR REPLACE PROCEDURE FOR_MUESTRO_1_10 
AS
BEGIN
  FOR CONT IN 1..10 LOOP
    DBMS_OUTPUT.PUT_LINE (CONT);
  END LOOP;
END;

CREATE OR REPLACE PROCEDURE FOR_SUMO_DEL_1_10 
AS
SUMA NUMBER;
BEGIN
  SUMA := 0;
  FOR CONT IN 1..10 LOOP
   SUMA := SUMA + CONT;
   DBMS_OUTPUT.PUT_LINE ('SUMO '||CONT||'LLEVO '||SUMA);
  END LOOP;
  DBMS_OUTPUT.PUT_LINE ('LA SUMA TOTAL ES ' ||SUMA);
END;

-- MOSTRAR LOS 10 PRIMEROS NÚMEROS PARES
  2, 4, 6, 8..... 20
  
CREATE OR REPLACE PROCEDURE WHILE_10_PRIMEROS_PARES 
AS
CONT NUMBER;
NUM_PAR NUMBER;
BEGIN
   NUM_PAR := 2;
   CONT := 0;
   WHILE (CONT < 10) LOOP
      DBMS_OUTPUT.PUT_LINE (NUM_PAR);
      CONT := CONT + 1;
      DBMS_OUTPUT.PUT_LINE ('HE MOSTRADO '||CONT);
      NUM_PAR := NUM_PAR + 2;
   END LOOP;
END;

CREATE OR REPLACE PROCEDURE FOR_10_PRIMEROS_PARES 
AS
NUM_PAR NUMBER;
BEGIN
   NUM_PAR := 2;
   FOR CONT IN 1..10 LOOP
      DBMS_OUTPUT.PUT_LINE (NUM_PAR);
      DBMS_OUTPUT.PUT_LINE ('HE MOSTRADO '||CONT);
      NUM_PAR := NUM_PAR + 2;
   END LOOP;
END;

CREATE OR REPLACE PROCEDURE FOR_10_PRIMEROS_PARES2 
AS
BEGIN
   FOR CONT IN 1..10 LOOP
      DBMS_OUTPUT.PUT_LINE (CONT*2);
   END LOOP;
END;
        