



CREATE OR REPLACE PROCEDURE FOR_MUESTRO_1_10 
AS
BEGIN
  VER ('LOS MUESTRO DE MENOR A MAYOR');
  FOR CONT IN 1..10 LOOP
    VER (CONT);
  END LOOP;
  VER ('LOS MUESTRO DE MAYOR A MENOR');
  FOR CONT IN REVERSE 1..10 LOOP
    VER (CONT);
  END LOOP;
END;
CREATE OR REPLACE PROCEDURE VER (ALGO VARCHAR2)
AS
BEGIN
 DBMS_OUTPUT.PUT_LINE(ALGO);
END; 

EXECUTE FOR_MUESTRO_1_10;


-- RECIBO 2 NUMEROS Y MUESTRO LOS MÚLTIPLOS DE 10 QUE HAY ENTRE ELLOS

MUESTRO_10 (35, 93)
MUESTRO_10 (93, 35)
muestro_10 (42, 42)

CREATE OR REPLACE PROCEDURE MUESTRO_10 (PNUM1 NUMBER, PNUM2 NUMBER)
AS
MENOR NUMBER;
MAYOR NUMBER;
CUANTOS NUMBER := 0;
TEXTO VARCHAR2(40);
BEGIN
IF PNUM1 < PNUM2 THEN 
   MENOR:=PNUM1;
   MAYOR:=PNUM2;
ELSE
   MENOR:=PNUM2;
   MAYOR:=PNUM1; 
END IF;  
FOR CONT IN MENOR..MAYOR LOOP
    IF MOD (CONT, 10) = 0 THEN 
       VER (CONT);
       TEXTO := TEXTO || CONT||',';
       CUANTOS := CUANTOS + 1;
    END IF;   
END LOOP;
TEXTO := SUBSTR (TEXTO,1,LENGTH(TEXTO)-1); 
IF CUANTOS > 0 THEN 
   VER ('HAY '||CUANTOS||' MULTIPLOS DE 10 QUE SON '||TEXTO);
ELSE
   VER ('HAY '||CUANTOS||' MULTIPLOS DE 10');
END IF;
END;
