BASE DE DATOS ORACLE

  APLICACION DE LA CLINICA VETERINARIA (8 TABLAS)
  APLICACION DE EL CORTE INGLES (800 TABLAS)
  APLICACION PARA REPSOL (1000 TABLAS ----- 8.000.000 DE REGISTROS DE DATOS)
  
  TRABAJAR CON TABLESPACES
  
  DESC DBA_TABLESPACES --VISTA CON INFORMACIÓN DE LOS TABLESPACES
  
SELECT * FROM DBA_TABLESPACES;

CREATE TABLESPACE PEQUE DATAFILE 'FPEQUE.DBF' SIZE 100K --EXTENSION HABITUAL DE ARCHIVOS DE DATOS DE TABLESPACE
AUTOEXTEND ON NEXT 120K MAXSIZE 1M; --IRSE HACIENDO MÁS GRANDE EN FUNCIÓN DE QUE LE VAYA METIENDO MÁS COSAS.


CREATE TABLE USUASIR.PERSONAL --LA ESTÁ CREANDO EN ASIR PARA NO TENER QUE CAMBIARME DE USUARIO (Q PEREZA)
(DNI VARCHAR2(9) PRIMARY KEY,
 NOMBRE VARCHAR2(40),
 TFNO VARCHAR2 (9))
 TABLESPACE PEQUE;
 
 INSERT INTO USUASIR.PERSONAL VALUES
 ('50034334P', 'RUBEN', 696834341);
 
 ALTER TABLESPACE PEQUE OFFLINE; --ONLINE

 SELECT * FROM USUASIR.DEPART;
 
 SELECT * FROM USUASIR.PERSONAL;
 
 DROP TABLESPACE PEQUE --ME AVISA DE QUE TIENE CONTENIDO Y SE BORRARÁ LA TABLA
 INCLUDING CONTENTS; --CONE STO ME DEJARÁ BORRARLO.
 
 --SI AHORA QUISIESEMOS CREAR OTRA VEZ EL TABLESPACE IGUAL, 
 --PUES ME SALDRÁ QUE EL ARCHIVO SIGUE ESTÁNDO COMO RESIDUO PQ YO SOLO HE BORRADO EL TABLESPACE
 CREATE TABLESPACE PEQUE DATAFILE 'FPEQUE.DBF' REUSE --LE PONEMOS REUSE PARA PODER USARLO
AUTOEXTEND ON NEXT 120K MAXSIZE 1M;

SELECT * FROM DBA_DATA_FILES;

--LOS OBJETOS QUE SE CREEN TIENEN QUE TENER ESTAS CARACTERISTICAS == DEFAULT STORAGE
--CUANDO CREE UN OBJETO ASOCIADO


CREATE TABLESPACE TRABAJO DATAFILE 'TRABAJO01.DBF' SIZE 10M
                                    'TRABAJO02' SIZE 5M