CREATE OR REPLACE PROCEDURE PINTAR_DEL_1_AL_10
AS
CONTADOR NUMBER;
BEGIN
CONTADOR:=1;
   DBMS_OUTPUT.PUT_LINE ('VOY A ENTRAR AL BUCLE');
LOOP
   DBMS_OUTPUT.PUT_LINE (CONTADOR);
   CONTADOR:= CONTADOR + 1;
   IF CONTADOR > 10 THEN
      DBMS_OUTPUT.PUT_LINE ('ME VOY...');
      EXIT;
   END IF;   
END LOOP;
END;

-- RECIBE UN NÚMERO Y MUESTRO LOS NÚMEROS DESDE EL 1 HASTA EL RECIBIDO
CREATE OR REPLACE PROCEDURE PINTAR_DEL_1_N (PNUM NUMBER)
AS
CONTADOR NUMBER;
BEGIN
IF PNUM >= 1 THEN
    CONTADOR:=1;
       DBMS_OUTPUT.PUT_LINE ('VOY A ENTRAR AL BUCLE');
    LOOP
       DBMS_OUTPUT.PUT_LINE (CONTADOR);
       CONTADOR:= CONTADOR + 1;
       IF CONTADOR > PNUM THEN
          DBMS_OUTPUT.PUT_LINE ('ME VOY...');
          EXIT;
       END IF;   
    END LOOP;
ELSE
   DBMS_OUTPUT.PUT_LINE('NO SIRVEN NÚMEROS NEGATIVOS, NI EL CERO');
END IF;
END;

        