--EXAMEN 2021
--------------------------------------------------------------------------------
--EJERCICIO 1
create or replace PROCEDURE EJ1_2021(DNI VARCHAR2, NOMBRE VARCHAR2, DIRECCION VARCHAR2, 
TELEFONO VARCHAR2)
AS
CONTADOR NUMBER :=0;
BEGIN
  IF DNI IS NULL THEN
    VER('ERROR');
    CONTADOR:=CONTADOR+1;
  END IF;
  
  IF NOMBRE IS NULL THEN
    VER('ERROR');
    CONTADOR:=CONTADOR+1;
  END IF;

  IF TELEFONO IS NULL THEN
    VER('ERROR');
    CONTADOR:=CONTADOR+1;
  END IF;

  IF SUBSTR(DNI,-1) NOT BETWEEN 'A' AND 'Z' THEN
    VER('ERROR');
    CONTADOR:=CONTADOR+1;
  END IF;
  
  IF SUBSTR(TELEFONO,1,2)<> 91 AND SUBSTR(TELEFONO,1,1)<> 6 AND SUBSTR(TELEFONO,1,1)<> 7 OR LENGTH(TELEFONO) <> 9 THEN
    VER('ERROR');
    CONTADOR:=CONTADOR+1;
  END IF;
  IF CONTADOR=0 THEN
    VER('NO HAY ERRORES');
  ELSE
    IF CONTADOR=3 THEN
      VER('YA TE VALE');
    END IF;
  END IF;
END;
EXECUTE EJ1_2021('51470807G','MARCO','DOLORES','667396687');
--------------------------------------------------------------------------------
--EJERCICIO 2
CREATE OR REPLACE PROCEDURE EJ2_2021(FECHA DATE)
AS
DIFERENCIA NUMBER;
BEGIN
  VER('DIA DE LA SEMANA: '||TO_CHAR(FECHA, 'DAY'));
  IF FECHA<SYSDATE THEN
    VER('LA FECHA ES MENOR QUE LA DEL SISTEMA');
  ELSE
    DIFERENCIA:=FECHA-SYSDATE;
    VER('LOS DÍAS QUE FALTAN: '||TRUNC(DIFERENCIA));
  END IF;
END;
EXECUTE EJ2_2021('1/03/2022');
--------------------------------------------------------------------------------
--EJERCICIO 3
CREATE OR REPLACE PROCEDURE EJ3_2021(NUMERO1 NUMBER)
AS
CONTADOR NUMBER :=0;
SUMA DATE:=SYSDATE-1;
BEGIN
  WHILE NUMERO1>0 AND CONTADOR<NUMERO1 LOOP
    CONTADOR:= CONTADOR+1;
    SUMA:= SUMA+1;
    VER(SUMA);
  END LOOP;
END;
EXECUTE EJ3_2021(6);
--------------------------------------------------------------------------------
--EJERCICIO 4
CREATE OR REPLACE PROCEDURE EX04(NUM1 NUMBER,NUM2 NUMBER)
AS
MENOR NUMBER;
MAYOR NUMBER;
CONTADOR NUMBER;
BEGIN
CONTADOR :=0;
MENOR :=0;
MAYOR :=0;
IF NUM1 < NUM2 THEN
MENOR :=NUM1;
MAYOR :=NUM2;
ELSE
MENOR :=NUM2;
MAYOR :=NUM1;
END IF;

FOR CONT IN MENOR..MAYOR LOOP
 IF MOD(CONT,3)=0 THEN
 VER (CONT);
 CONTADOR := CONTADOR +1;
 END IF;
END LOOP;
VER ('EN TOTAL HAY ' || CONTADOR);
END;

