DROP TABLE MOVIMIENTOS;
DROP TABLE CUENTAS;
DROP TABLE CLIENTES;
DROP TABLE SUCURSALES;

CREATE TABLE SUCURSALES
(NUM_SUCURSAL CHAR(3) PRIMARY KEY,
DIRECCION VARCHAR2(30) NOT NULL,
DIRECTOR VARCHAR2(30) NOT NULL,
CONSTRAINT CK_suc_NUMSUCURSAL CHECK (LENGTH(NUM_SUCURSAL)=3 
                                AND SUBSTR(NUM_SUCURSAL,1,1)<>0),
    --      NUM_SUCURSAL BETWEEN 100 AND 999  
CONSTRAINT CK_SUC_DIRECCION CHECK (DIRECCION = UPPER(DIRECCION)),
CONSTRAINT CK_SUC_DIRECTOR CHECK (DIRECTOR = UPPER(DIRECTOR))
);


CREATE TABLE CLIENTES
(NIF VARCHAR2(9) PRIMARY KEY,
Nombre VARCHAR2(30),
Direccion VARCHAR2(50),
Telefono VARCHAR2(9),
CONSTRAINT CK_CLI_NIF CHECK(SUBSTR(NIF,-1)BETWEEN 'A' AND 'Z'),
CONSTRAINT CK_CLI_TELEFONO CHECK(LENGTH(TELEFONO)=9 AND SUBSTR(TELEFONO,1,1)<>8)
);

CREATE TABLE CUENTAS
(NUM_CUENTA CHAR(24) PRIMARY KEY,
NIF_TITULAR VARCHAR2(9) NOT NULL REFERENCES CLIENTES,
NIF_COTITULAR VARCHAR2(9) REFERENCES CLIENTES,
FECHA_ABIERTA DATE DEFAULT SYSDATE,
NUM_SUCURSAL CHAR(3) REFERENCES SUCURSALES,
TIPO CHAR(1),
SALDO NUMBER(*,2),
CONTROL CHAR(1) NOT NULL,
CONSTRAINT CK_CUE_FECHAABIERTA CHECK(TO_CHAR(FECHA_ABIERTA,'D')<>6 AND
                                 TO_CHAR(FECHA_ABIERTA,'D')<>7),
   --   TO_CHAR(FECHA_ABIERTA,'D') BETWEEN 1 AND 5                           
CONSTRAINT CK_CUE_TIPO CHECK (TIPO IN( 'C','P','F')),
CONSTRAINT CK_CUE_SALDO CHECK (SALDO >= -100000),
CONSTRAINT CK_CONTROL CHECK (CONTROL IN ('A', 'B'))
);

CREATE TABLE MOVIMIENTOS
(NUM_CUENTA CHAR(24) REFERENCES CUENTAS,
 FECHAHORA DATE DEFAULT SYSDATE,
 IMPORTE NUMBER (*,2) NOT NULL,
 CONCEPTO VARCHAR2(60) DEFAULT 'FALTA CONCEPTO' NOT NULL,
 NUM_SUCURSAL CHAR(3) REFERENCES SUCURSALES,
 CONSTRAINT PK_MOVIMIENTOS PRIMARY KEY (NUM_CUENTA, FECHAHORA));











   
   
  