CREATE OR REPLACE PROCEDURE ALTA_DEPART (PNUM NUMBER, PNOMBRE VARCHAR2, PLOC VARCHAR2)
AS
CUANTOS NUMBER;
BEGIN
IF PNUM BETWEEN 1 AND 99 THEN
    SELECT COUNT(*) INTO CUANTOS
       FROM DEPART
         WHERE DEPT_NO = PNUM;
    IF CUANTOS > 0 THEN 
       VER ('EL NÚMERO DE DEPARTAMETO YA EXISTE');
    ELSE
        INSERT INTO DEPART
          VALUES (PNUM, PNOMBRE, PLOC);
        VER ('DEPARTAMENTO DADO DE ALTA');   
    END IF;    
ELSE
   VER ('ERROR, NÚMERO NO VALIDO');
END IF;
END;


EXECUTE ALTA_DEPART (10,'ADMINISTRACION','MADRID');

SELECT * FROM DEPART;

CREATE OR REPLACE PROCEDURE CAMBIA_LOCALIDAD (PNUM NUMBER, PLOC VARCHAR2)
AS
CUANTOS NUMBER;
BEGIN
-- AÑADIR UNA VALIDACIÓN PARA COMPROBAR SI EXISTE O NO EL DEPARTAMENTO
-- SI NO EXISTE SE MUESTRA UN MENSAJE Y NO HACEMOS EL UPDATE
SELECT COUNT(*) INTO CUANTOS
   FROM DEPART
      WHERE DEPT_NO = PNUM;
IF CUANTOS > 0 THEN 
    UPDATE DEPART
     SET LOC = PLOC
       WHERE DEPT_NO = PNUM;   
    VER ('DEPARTAMENTO MODIFICADO');   
ELSE
   VER ('NO EXISTE EL DEPARTAMENTO QUE QUIERE MODIFICAR');
END IF; 
END;

EXECUTE CAMBIA_LOCALIDAD (70, 'ALCOBENDAS');


SELECT * FROM DEPART;

PROCEDIMIENTO PARA DAR DE BAJA (BORRAR) UN DEPARTAMENTO
RECIBE UN NÚMERO DE DEPARTAMENTO
COMPRUEBA QUE EXISTA, SI NO EXISTE DAMOS UN MENSAJE DE ERROR Y NO HACE NADA MAS
SI EXISTE COMPROBAR SI TIENE EMPLEADOS
   SI LOS TIENE NO SE PUEDE BORRAR EL DEPARTAMENTO, DAR UN MENSAJE DE ERROR
   SI NO TIENE EMPLEADOS BORRAMOS EL DEPARTAMENTO Y DAMOS UN MENSAJE DE QUE LO HEMOS BORRADO
   
FUNCIÓN QUE RECIBE UN NÚMERO Y DEVUELVE CUANTOS DEPARTAMENTOS TIENE ESE NÚMERO
    F_NUM_DEPART (10) --->  1
    F_NUM_DEPART (33) --->  0  

CREATE OR REPLACE FUNCTION F_NUM_DEPART (PNUM NUMBER)
RETURN NUMBER
IS
CUANTOS NUMBER;
BEGIN
  SELECT COUNT(*) INTO CUANTOS
    FROM DEPART
      WHERE DEPT_NO = PNUM;
  RETURN CUANTOS;
END;  

SELECT F_NUM_DEPART (12)
  FROM DUAL;



CREATE OR REPLACE PROCEDURE BAJA_DEPART_V2 (PNUM NUMBER)  
AS
CUANTOS NUMBER;
BEGIN
 
  IF F_NUM_DEPART(PNUM) = 0 THEN 
     VER ('NO EXISTE EL DEPARTAMENTO NO EXISTE');
  ELSE
     -- VOY A VER SI TIENE EMPLEADOS
     SELECT COUNT(*) INTO CUANTOS 
        FROM EMPLE
          WHERE DEPT_NO = PNUM;
     IF CUANTOS > 0 THEN 
        VER ('TIENE EMPLEADOS, NO PUEDO BORRARLO');
     ELSE
        DELETE DEPART
          WHERE DEPT_NO = PNUM;
        VER ('DEPARTAMENTO BORRADO');  
     END IF;
  END IF;    
END;          
     
CREATE OR REPLACE PROCEDURE BAJA_DEPART (PNUM NUMBER)  
AS
CUANTOS NUMBER;
BEGIN
  SELECT COUNT(*) INTO CUANTOS
    FROM DEPART
      WHERE DEPT_NO = PNUM;
  IF CUANTOS = 0 THEN 
     VER ('NO EXISTE EL DEPARTAMENTO NO EXISTE');
  ELSE
     -- VOY A VER SI TIENE EMPLEADOS
     SELECT COUNT(*) INTO CUANTOS 
        FROM EMPLE
          WHERE DEPT_NO = PNUM;
     IF CUANTOS > 0 THEN 
        VER ('TIENE EMPLEADOS, NO PUEDO BORRARLO');
     ELSE
        DELETE DEPART
          WHERE DEPT_NO = PNUM;
        VER ('DEPARTAMENTO BORRADO');  
     END IF;
  END IF;    
END;  
EXECUTE BAJA_DEPART (70);

