--EJERCICIO 1
SELECT IDENT_ANIMAL||'-'||RAZA||'('||SUBSTR(ESPECIE,1,3)||')', TO_CHAR(FECHA_NACIMIENTO, 'MONTH - YYYY'), SUBSTR(TFNO_CONTACTO, 1, 3)||'***'||SUBSTR(TFNO_CONTACTO, 6, 3)
  FROM ANIMALES JOIN DUEÑOS ON DUEÑOS.DNI = ANIMALES.DNI_DUEÑO
      ORDER BY TO_CHAR(FECHA_NACIMIENTO, 'YYYY'), RAZA;
      
--EJERCICIO 2
SELECT TRUNC(SYSDATE-FH_VISITA), ANIMALES.NOMBRE, VETERINARIOS.NOMBRE, TO_CHAR(FH_VISITA, 'DAY')
  FROM VETERINARIOS JOIN VISITAS ON VISITAS.NUMCOLEGIADO = VETERINARIOS.NUMCOLEGIADO
    JOIN ANIMALES ON ANIMALES.IDENT_ANIMAL = VISITAS.IDENT_ANIMAL
  WHERE TO_CHAR(FH_VISITA, 'HH24') < 15
    AND MOTIVO IN ('REVISION', 'VACUNA', 'GASTRITIS');

--EJERCICIO 3
SELECT DNI, DUEÑOS.NOMBRE, COUNT(*)
  FROM DUEÑOS JOIN ANIMALES ON ANIMALES.DNI_DUEÑO = DUEÑOS.DNI
    WHERE ESPECIE LIKE 'PERRO'
      GROUP BY DNI, DUEÑOS.NOMBRE
        HAVING COUNT(*) = (SELECT MAX(COUNT(*))
                            FROM DUEÑOS JOIN ANIMALES ON ANIMALES.DNI_DUEÑO = DUEÑOS.DNI
                              WHERE ESPECIE LIKE 'PERRO'
                                GROUP BY DNI, DUEÑOS.NOMBRE);
                                
--EJERCICIO 4
SELECT VISITAS.IDENT_ANIMAL, COUNT(FH_VISITA), MIN(FH_VISITA), MAX(FH_VISITA), SUM(PRECIO), COUNT(MOTIVO)
  FROM VISITAS JOIN ANIMALES ON ANIMALES.IDENT_ANIMAL = VISITAS.IDENT_ANIMAL
    WHERE ESPECIE LIKE 'GATO'
      GROUP BY VISITAS.IDENT_ANIMAL;
      
--EJERCICIO 5
INSERT INTO VISITAS
  SELECT VISITAS.IDENT_ANIMAL, TO_DATE(1002202210, 'DD/MM/YYYY HH24'), 3443, 'REVISION', NULL, NULL
    FROM VISITAS JOIN ANIMALES ON ANIMALES.IDENT_ANIMAL = VISITAS.IDENT_ANIMAL
      WHERE NOMBRE LIKE 'GRESCA'
        AND ESPECIE LIKE 'PERRO';

--EJERCICIO 6 --- A
INSERT INTO VETERINARIOS
  SELECT 4466, 'ESTHER FLORES', TFNO_CONTACTO
    FROM DUEÑOS
      WHERE TFNO_CONTACTO = (SELECT TFNO_CONTACTO
                          FROM DUEÑOS
                            WHERE NOMBRE LIKE 'Esther%');
                            
--EJERCICIO 6 --- B
UPDATE ANIMALES
  SET DNI_DUEÑO = (SELECT DNI 
                      FROM DUEÑOS
                        WHERE NOMBRE LIKE 'Esther%')
  WHERE NOMBRE LIKE 'GRESCA'
    AND ESPECIE LIKE 'PERRO';


--EJERCICIO 7 --- A
DELETE VISITAS
  WHERE IDENT_ANIMAL IN (SELECT IDENT_ANIMAL
                            FROM ANIMALES
                              WHERE ESPECIE LIKE 'PERRO')
    AND TO_CHAR(FH_VISITA, 'MM')= TO_CHAR(SYSDATE, 'MM') -10;

--EJERCICIO 7 --- B
DELETE ANIMALES
  WHERE IDENT_ANIMAL NOT IN (SELECT IDENT_ANIMAL
                                FROM VISITAS);
  
