--EJERCICIO 1
SELECT SUBSTR(MATRICULA,1,4)||'-'||SUBSTR(MATRICULA,5,3), NOMBRE, TRUNC((SYSDATE-FECHA_ALTA)/365.25)
  FROM COCHES_TALLER JOIN CLIENTES_TALLER ON CLIENTES_TALLER.NCLIENTE = COCHES_TALLER.NCLIENTE
    WHERE MODELO LIKE 'CITROEN%';
    
--EJERCICIO 2
SELECT TO_CHAR(FECHA_ENTRADA, 'HH24:MI'), TO_CHAR(FECHA_ENTRADA, 'DAY'), 
  IMPORTE-(IMPORTE*(8/100)), ROUND(IMPORTE-IMPORTE*8/100,1), COCHES_TALLER.MATRICULA, MODELO
    FROM MECANICOS JOIN ARREGLOS ON ARREGLOS.NEMPLEADO = MECANICOS.NEMPLEADO
      JOIN COCHES_TALLER ON COCHES_TALLER.MATRICULA = ARREGLOS.MATRICULA
        WHERE FUNCION LIKE 'CHAPISTA'
          OR FUNCION LIKE 'LUNAS';
          
--EJERCICIO 3 MAL
SELECT COUNT(FECHA_ENTRADA), MAX(IMPORTE), MIN(IMPORTE), COUNT(DISTINCT(MATRICULA)), SUM(IMPORTE)
  FROM ARREGLOS
    WHERE FECHA_ENTRADA BETWEEN '01/01/2020' AND '31/12/2020'; --MAL
    --EJER 3 BIEN:
    SELECT COUNT(FECHA_ENTRADA), MAX(IMPORTE), MIN(IMPORTE), COUNT(DISTINCT(MATRICULA)), SUM(IMPORTE)
      FROM ARREGLOS
        WHERE TO_CHAR(FECHA_ENTRADA, 'YYYY') = 2020;
  
--EJERCICIO 4
SELECT NOMBRE
  FROM CLIENTES_TALLER 
    WHERE NCLIENTE NOT IN (SELECT NCLIENTE FROM COCHES_TALLER WHERE AÑO_MATRICULA = 2015);
    
--EJERCICIO 5
SELECT NEMPLEADO
  FROM MECANICOS
    WHERE (FECHA_ING > (SELECT FECHA_ING FROM MECANICOS WHERE NOMBRE LIKE 'RAMON%')
      OR FUNCION = (SELECT FUNCION FROM MECANICOS WHERE NOMBRE LIKE 'RAMON%'))
      AND NOMBRE NOT LIKE 'RAMON%';
    
    
    
    
    
    
    
    