CREATE OR REPLACE PROCEDURE EJERCICIO_12(PBASE NUMBER, PALTURA NUMBER)
AS
  AREA NUMBER;
BEGIN
  IF  PBASE > 0  AND PALTURA > 0  THEN
      AREA := ((PBASE * PALTURA) / 2);
      DBMS_OUTPUT.put_line('Buenos días, procedamos a calcular el área de un triángulo:');
      DBMS_OUTPUT.put_line('La base del triángulo con tus medidas será: ' || AREA || ' metros');
  ELSE
    DBMS_OUTPUT.put_line('Por favor, haga el favor de introducir valores positivos');
    DBMS_OUTPUT.put_line('Error con los datos introducidos');
  END IF;
END;

EXECUTE EJERCICIO_12(10,5);


CREATE OR REPLACE PROCEDURE EJERCICIO_13(NOTA1 NUMBER, NOTA2 NUMBER, NOTA3 NUMBER)
AS
  RESULTADO NUMBER;
  MEDIA NUMBER;
BEGIN
  IF (NOTA1 BETWEEN 0 AND 10) THEN
    IF (NOTA2 BETWEEN 0 AND 10) THEN
      IF (NOTA3 BETWEEN 0 AND 10) THEN
        RESULTADO := ((NOTA1 + NOTA2 + NOTA3) / 3);
        MEDIA := (ROUND(RESULTADO,2));
        DBMS_OUTPUT.put_line('Buenos días, procedamos a calcular la nota de BBDD: ');
        DBMS_OUTPUT.put_line('La nota redondeada será: ' || MEDIA );
        ELSE
          DBMS_OUTPUT.put_line('Error EN LA TERCERA NOTA, introduce valores entre 0 y 10');
        END IF;
      ELSE
        DBMS_OUTPUT.put_line('Error EN LA SEGUNDA NOTA, introduce valores entre 0 y 10');
      END IF;
    ELSE
      DBMS_OUTPUT.put_line('Error EN LA PRIMERA NOTA, introduce valores entre 0 y 10');
    END IF;
END;


CREATE OR REPLACE PROCEDURE EJERCICIO_13_2(NOTA1 NUMBER, NOTA2 NUMBER, NOTA3 NUMBER)
AS
  MEDIA NUMBER;
  CONTADOR NUMBER:=0;
BEGIN
-- DAR ERROR POR CADA NOTA MAL
-- CONTABILIZAR LOS ERRORES
  IF  NOTA1 NOT BETWEEN 0 AND 10  THEN
    CONTADOR:=CONTADOR +1;
     DBMS_OUTPUT.put_line('Error EN LA PRIMERA NOTA, introduce valores entre 0 y 10');
  END IF; 
   IF  NOTA2 NOT BETWEEN 0 AND 10  THEN
    CONTADOR:=CONTADOR +1;
     DBMS_OUTPUT.put_line('Error EN LA SEGUNDA NOTA, introduce valores entre 0 y 10');
  END IF; 
  IF  NOTA3 NOT BETWEEN 0 AND 10  THEN
    CONTADOR:=CONTADOR +1;
     DBMS_OUTPUT.put_line('Error EN LA TERCERA NOTA, introduce valores entre 0 y 10');
  END IF;
  IF CONTADOR = 0 THEN
        MEDIA :=  ROUND(((NOTA1 + NOTA2 + NOTA3) / 3),2) ;
        DBMS_OUTPUT.put_line('Buenos días, procedamos a calcular la nota de BBDD: ');
        DBMS_OUTPUT.put_line('La nota redondeada será: ' || MEDIA );
   ELSE
      VER ('HAS TENIDO '||CONTADOR||' NOTAS ERRONEAS'); 
   END IF;
END;

EXECUTE EJERCICIO_13_2(5.25,  4.5, 9.75);

8--

CREATE OR REPLACE PROCEDURE EJER_08(PNUM NUMBER) AS

BEGIN

IF PNUM < 0 THEN
  DBMS_OUTPUT.PUT_LINE ('EL NUMERITO NO PUEDE SER NEGATIVO');
ELSE
  DBMS_OUTPUT.PUT_LINE ('MULTIPLICADO POR 10:  '||(PNUM*10));
  DBMS_OUTPUT.PUT_LINE ('MULTIPLICADO POR 100:  '||(PNUM*100));
  DBMS_OUTPUT.PUT_LINE ('MULTIPLICADO POR 1000:  '||(PNUM*1000));
END IF;

END;



EXECUTE EJER_08(3);



9--


CREATE OR REPLACE PROCEDURE EJER_09 (PPRECIO NUMBER,PPORCENTAJE NUMBER)
AS
RESULTADO NUMBER;
BEGIN
IF PPORCENTAJE NOT BETWEEN 0 AND 100 THEN
   DBMS_OUTPUT.PUT_LINE ('EL PORCENTAJE TIENE QUE ESTAR ENTRE 0 Y 100');
ELSE
   RESULTADO:=(PPRECIO+(PPRECIO*(PPORCENTAJE)/100));
   DBMS_OUTPUT.PUT_LINE ('EL INCREMENTO REALIZADO ES DE:  '||RESULTADO);
END IF;
END;


EXECUTE EJER_09(100,22);

-EJER_10
CREATE OR REPLACE PROCEDURE EJER_10 (NUMERO1 NUMBER, NUMERO2 NUMBER)
AS
BEGIN
IF NUMERO1 = NUMERO2 THEN DBMS_OUTPUT.PUT_LINE('LOS DOS NUMEROS SON IGUALES');

ELSE
  IF NUMERO1 > NUMERO2 THEN DBMS_OUTPUT.PUT_LINE(NUMERO1||' ES MAYOR QUE '||NUMERO2);
 
  ELSE
  DBMS_OUTPUT.PUT_LINE(NUMERO2||' ES MAYOR QUE '||NUMERO1);
 
  END IF;
END IF;
END;

EXECUTE EJER_10(20,20);

--EJER_11
CREATE OR REPLACE PROCEDURE EJER_11 (PALABRA1 VARCHAR2, PALABRA2 VARCHAR2)
AS
BEGIN
DBMS_OUTPUT.PUT_LINE('LA PALABRA ES '||PALABRA1||' TIENE ESTOS CARACTERES '||LENGTH(PALABRA1));
DBMS_OUTPUT.PUT_LINE('LA PALABRA ES '||PALABRA2||' TIENE ESTOS CARACTERES '||LENGTH(PALABRA2));
IF  LENGTH(PALABRA1) = LENGTH(PALABRA2) THEN
   DBMS_OUTPUT.PUT_LINE('TIENEN LA MISMA LONGITUD');
ELSE
   IF  LENGTH(PALABRA1)  < LENGTH(PALABRA2) THEN
      DBMS_OUTPUT.PUT_LINE('LA PALABRA MÁS LARGA ES '||PALABRA2);
   ELSE 
      DBMS_OUTPUT.PUT_LINE('LA PALABRA MÁS LARGA ES '||PALABRA1);
   END IF;
END IF;
END;

EXECUTE EJER_11('CALABAZAS','AGUACATE');
