/*CURSORES
1. PROCEDIMIENTO QUE MUESTRA TODOS LOS DEPARTAMENTOS*/
CREATE OR REPLACE PROCEDURE MOSTRAR_DEPARTAMENTOS
AS
  CURSOR PACO IS
    SELECT *
      FROM DEPART;

BEGIN
  FOR I IN PACO LOOP
    VER(I.DNOMBRE || ' ' || I.DEPT_NO||' '||I.LOC);
  END LOOP;
END;

EXECUTE MOSTRAR_DEPARTAMENTOS;
/*2. PROCEDIMIENTO QUE RECIBE UN NÚMERO DE DEPARTAMENTO Y MUESYTA EL APELLIDO, SALARIO Y
OFICIO DE LOS EMPLEADOS DE ESE DEPART*/
CREATE OR REPLACE PROCEDURE EJ2_CURSOR (PNUMERO NUMBER)
AS
  CURSOR PACO IS
    SELECT *
      FROM EMPLE
        WHERE DEPT_NO = PNUMERO;
BEGIN
  FOR I IN PACO LOOP
    VER (I.APELLIDO||' '||I.SALARIO||' '||I.OFICIO);
  END LOOP;
END;

EXECUTE EJ2_CURSOR(20);

/*3. AÑADIR EN EL ANTERIOR QUE AL FINAL DE MOSTRAR DIGA CUANTOS EMPLEADOS HA MOSTRADO 
Y LA SUMA DE SUS SALARIOS*/
CREATE OR REPLACE PROCEDURE EJ3_CURSOR (PNUMERO NUMBER)
AS
  CURSOR PACO IS
    SELECT *
      FROM EMPLE
        WHERE DEPT_NO = PNUMERO;
  CONTADOR NUMBER:=0;
  SALARIO NUMBER:=0;
BEGIN
  FOR I IN PACO LOOP
    VER (I.APELLIDO||' '||I.SALARIO||' '||I.OFICIO);
    CONTADOR:=CONTADOR+1;
    SALARIO:=SALARIO+I.SALARIO;
  END LOOP;
  VER('HAY '||CONTADOR||' EMPLEADOS Y LA SUMA DE SUS SALARIOS ES '||SALARIO);
END;

EXECUTE EJ3_CURSOR(20);

--CURSORES II

CREATE OR REPLACE PROCEDURE VER_DEPARTAMENTOS_81
AS
  CURSOR CUR_D IS
    SELECT DEPT_NO, DNOMBRE
      FROM DEPART;
  VAUX NUMBER;   
  CURSOR CUR_E IS
    SELECT APELLIDO, SALARIO, DEPT_NO
      FROM EMPLE
        WHERE DEPT_NO = VAUX;
BEGIN

FOR I IN CUR_D LOOP
  VER(I.DEPT_NO||' '||I.DNOMBRE);
  VAUX:=I.DEPT_NO;
  FOR J IN CUR_E LOOP
    VER(J.APELLIDO||' '||J.SALARIO);
  END LOOP;
END LOOP;
END;

EXECUTE VER_DEPARTAMENTOS_81();














