/*EJERCICIOS CURSORES I
EJERCICIO 1: PROCEDIMIENTO QUE RECIBE UNA ESPECIE Y MUESTRA LOS ANIMALES DE ESA ESPECIE
SACA EL NOMBRE, LA RAZA Y EL SEXO. AL FINAL MUESTRA CUANTOS HAY
    AÑADIR LO NECESARIO PARA MOSTRAR LA EDAD DE CADA ANIMAL
    AÑADIR LO NECESARIO PARA MOSTRAR CUANTAS HEMBRAS HAY ('H') Y CUANTOS  MACHOS ('M')*/
create or replace PROCEDURE EJ_1_CURSOR (PESPECIE VARCHAR2)
AS
  CURSOR CUR_1 IS
    SELECT NOMBRE, RAZA, SEXO, TRUNC((SYSDATE-FECHA_NACIMIENTO)/365) EDAD
      FROM ANIMALES
        WHERE PESPECIE = ESPECIE;
  CONTADOR NUMBER:=0;
  HEMBRAS NUMBER:=0;
  MACHOS NUMBER:=0;
BEGIN
  FOR I IN CUR_1 LOOP
    VER(I.NOMBRE||' '||I.RAZA||' '||I.SEXO||' EDAD: '||I.EDAD);
    CONTADOR:=CONTADOR+1;
    IF I.SEXO='H' THEN
      HEMBRAS:=HEMBRAS+1;
    ELSE
      MACHOS:=MACHOS+1;
    END IF;
  END LOOP;
  VER('HAY '||CONTADOR||' ANIMALES DE ESTA ESPECIE '||HEMBRAS||' HEMBRAS Y '||MACHOS||' MACHOS');
  
END;

EXECUTE EJ_1_CURSOR ('PERRO');

/*EJERCICIO 2: PROCEDIMIENTO QUE RECIBE UN DNI Y SACA LAS NOTAS DE ESE DNI, 
MUESTRA ADEMÁS EL NOMBRE DE LA ASIGNATURA DE CADA NOTA Y AL FINAL LA NOTA MEDIA 
Y EL NOMBRE DEL ALUMNO.*/
create or replace PROCEDURE EJ_2_CURSOR(PDNI VARCHAR2)
AS
  CURSOR CUR_2 IS
    SELECT NOTA, NOMBRE, APENOM
      FROM ASIGNATURAS JOIN NOTAS ON ASIGNATURAS.COD = NOTAS.COD
        JOIN ALUMNOS ON NOTAS.DNI = ALUMNOS.DNI
          WHERE NOTAS.DNI=PDNI;
          
  VMEDIA NUMBER;
BEGIN
  FOR I IN CUR_2 LOOP
   SELECT AVG(NOTA) INTO VMEDIA
      FROM NOTAS
          WHERE NOTAS.DNI=PDNI;
    VER('LA NOTA DE '||I.NOMBRE||' ES '||I.NOTA);
    VER('SU NOMBRE ES '||I.APENOM||' Y LA NOTA MEDIA '||VMEDIA);
  END LOOP;
END;

EXECUTE EJ_2_CURSOR ('12344345H');

/*EJERCICIO 3: PROCEDIMIENTO QUE RECIBE UNA ZONA DEL PARQUE DE ATRACCIONES Y MUESTRA 
LAS ATRACCIONES DE DICHA ZONA. MUESTRA EL CÓDIGO, EL NOMBRE Y CUANTOS AÑOS HACE 
DE SU INAUGURACIÓN. AL ACABAR DICE CUANTOS ATRACCIONES HAY Y EL NOMBRE 1
DEL ENCARGADO DE LA ZONA.*/
create or replace PROCEDURE EJ_3_CUR (PZONA VARCHAR2)
AS
  CURSOR CUR_3 IS
    SELECT NOM_ATRACCION, COD_ATRACCION, TRUNC((SYSDATE-FECHA_INAUGURACION)/365) ANOS
      FROM ATRACCIONES
        WHERE NOM_ZONA = PZONA;
  CONTADOR NUMBER:=0;
BEGIN
  FOR I IN CUR_3 LOOP
    VER('EL NOMBRE DE LA ATRACCION ES '||I.NOM_ATRACCION||' EL CODIGO '||I.COD_ATRACCION||' Y LLEVA '||I.ANOS||' AÑOS INAGURADA');
    CONTADOR:=CONTADOR+1;
  END LOOP;
    VER('EN ESTA ZONA HAY '||CONTADOR||' ATRACCIONES');
END;

EXECUTE EJ_3_CUR('Infantil');

/*EJERCICIO 4: PROCEDIMIENTO QUE MUESTRA, POR CADA DEPARTAMENTO, SU NOMBRE, 
SUMA DE SALARIOS, MEJOR SALARIO Y PEOR SALARIO.*/
CREATE OR REPLACE PROCEDURE EJ_4_CUR
AS
  CURSOR CUR_4 IS
    SELECT DNOMBRE, TRUNC(AVG(SALARIO)) MEDIA, TRUNC(MAX(SALARIO)) MEJOR, TRUNC(MIN(SALARIO)) PEOR
      FROM DEPART JOIN EMPLE ON DEPART.DEPT_NO = EMPLE.DEPT_NO
        GROUP BY DNOMBRE;
BEGIN
  FOR I IN CUR_4 LOOP
    VER('EL DEPARTAMENTO '||I.DNOMBRE||' SU SALARIO TOTAL ES '
    ||I.MEDIA||' Y EL MEJOR SALARIO '||I.MEJOR||' Y EL PEOR SALARIO '||I.PEOR);
  END LOOP;
END;

EXECUTE EJ_4_CUR;

/*EJERCICIO 5: PROCEDIMIENTO QUE RECIBE EL NOMBRE DE UN CLIENTE Y LLAMA A UNA FUNCIÓN 
PASÁNDOLE ESE NOMBRE. LA FUNCIÓN DEVOLVERÁ EL NÚMERO DE CLIENTE SI EXISTE Y SI NO NULL.

SI LA FUNCIÓN HA DEVUELTO UN NÚMERO DE CLIENTE SE MUESTRAN TODAS LOS ARREGLOS DE LOS COCHES 
DE ESE CLIENTE: 

MATRICULA, FECHA DE ENTRADA, FECHA DE SALIDA, DIAS EN EL TALLER, COSTE DEL ARREGLO
AL ACABAR SE MUESTRAN CUANTOS ARREGLOS TERMINADOS HA TENIDO Y CUANTOS ESTAN SIN FINALIZAR
MOSTRAR TAMBIÉN LA SUMA DE LOS IMPORTES*/

CREATE OR REPLACE FUNCTION F5 (PNOMBRE VARCHAR2)
RETURN NUMBER
IS
CLIENTE NUMBER;
BEGIN
SELECT NCLIENTE INTO CLIENTE
FROM CLIENTES_TALLER
WHERE NOMBRE = PNOMBRE;
RETURN CLIENTE;

EXCEPTION
WHEN NO_DATA_FOUND THEN
RETURN NULL;
END;

CREATE OR REPLACE PROCEDURE EJERCICIO5 (PNOMBRE VARCHAR2)
AS
FANTERIOR NUMBER;
CURSOR CLIENTE
    IS SELECT C.MATRICULA,FECHA_ENTRADA,FECHA_SALIDA,TRUNC((FECHA_SALIDA-FECHA_ENTRADA)/365) EDAD
    FROM COCHES_TALLER C, ARREGLOS A, CLIENTES_TALLER T
    WHERE C.MATRICULA = A.MATRICULA
    AND C.NCLIENTE = T.NCLIENTE
    AND NOMBRE = PNOMBRE;
BEGIN
FANTERIOR := F5(PNOMBRE);

IF FANTERIOR IS NULL THEN
VER('NO ESTA');
ELSE
FOR I IN CLIENTE LOOP
VER(I.MATRICULA || ' ' || I.FECHA_ENTRADA || ' ' || I.FECHA_SALIDA || ' ' ||I.EDAD );
END LOOP;
END IF;
END;



