--EXAMEN 2020
--------------------------------------------------------------------------------  
--EJERCICIO 1
create or replace PROCEDURE EJ1_2020(NUMERO1 NUMBER, NUMERO2 NUMBER, LETRA CHAR)
AS

BEGIN
  IF LETRA NOT IN ('A','B','C') THEN
    VER('ERROR DE LETRA');
  END IF;
  IF (NUMERO1<0) AND (NUMERO2<0) AND (NUMERO1 = NUMERO2) THEN
    VER('NUMEROS NO CORRECTOS');
  END IF;
    
  IF LETRA='A' THEN
    VER('OPCIÓN A: '||NUMERO1*NUMERO2);
  END IF;
  
  IF LETRA='B' THEN
    IF NUMERO1<NUMERO2 THEN 
      VER('OPCIÓN B: '||(NUMERO1*NUMERO2-NUMERO1));
    ELSE
      VER('OPCIÓN B: '||(NUMERO1*NUMERO2-NUMERO2));
    END IF;
  END IF;
  
  IF LETRA='C' THEN
    IF NUMERO1<NUMERO2 THEN 
      VER('OPCIÓN C: '||(NUMERO1*NUMERO2-NUMERO1)/2);
    ELSE
      VER('OPCIÓN C: '||(NUMERO1*NUMERO2-NUMERO1)/2);
    END IF;
  END IF;
END;

EXECUTE EJ1_2020 (2,4,'C');
--------------------------------------------------------------------------------
create or replace PROCEDURE EJ2_2020(USUARIO VARCHAR2, CONTRASENA VARCHAR2, REPITECONTRASENA VARCHAR2, COD_POSTAL VARCHAR2)
AS
CONTADOR NUMBER:=0;
BEGIN
  IF USUARIO IS NULL OR CONTRASENA IS NULL OR REPITECONTRASENA IS NULL OR COD_POSTAL IS NULL THEN
    VER('ERROR NULO');
    CONTADOR:=CONTADOR+1;
  END IF;
  IF CONTRASENA != REPITECONTRASENA OR LENGTH(CONTRASENA)<6 THEN
    VER('ERROR CONTRASEÑA');
    CONTADOR:=CONTADOR+1;
  END IF;
  IF LENGTH(COD_POSTAL) != 5 THEN
    VER('ERROR COD_POSTAL');
    CONTADOR:=CONTADOR+1;
  END IF;
  IF SUBSTR(USUARIO,1,2) != 'PC' THEN
    VER('ERROR USUARIO');
    CONTADOR:=CONTADOR+1;
  END IF;
  
  IF CONTADOR=0 THEN
    VER('BIENVENIDO AL SISTEMA');
  ELSE
    VER('ERRORES: '||CONTADOR);
  END IF;
END;

EXECUTE EJ2_2020('CMARCO','1234567890','1234567890','2803');
--------------------------------------------------------------------------------
--EJERCICIO 3
CREATE OR REPLACE PROCEDURE EJ3_2020(NUMERO1 NUMBER, NUMERO2 NUMBER)
AS
MENOR NUMBER;
MAYOR NUMBER;
BEGIN
  IF NUMERO1<NUMERO2 THEN
    MENOR:= NUMERO1;
    MAYOR:= NUMERO2;
  ELSE
    MENOR:= NUMERO2;
    MAYOR:= NUMERO1;
  END IF;
  
  FOR CONT IN MENOR..MAYOR LOOP
    VER('NUMERO: '||CONT);
    VER('CUADRADO: '||CONT*CONT);
    VER('CUBO: '||CONT*CONT*CONT);
  END LOOP;
END;

EXECUTE EJ3_2020(2,4);
--------------------------------------------------------------------------------
--EJERCICIO 4
CREATE OR REPLACE PROCEDURE EJ4_2020(FECHA DATE)
AS
CUMPLEAÑOS NUMBER:=0;
EDAD NUMBER:=0;
BEGIN
  CUMPLEAÑOS:=TRUNC((SYSDATE-FECHA)/365)+10;
  
  FOR CONT IN 1..CUMPLEAÑOS LOOP
    IF MOD(CONT,10)=0 THEN
    CUMPLEAÑOS:=CONT;
    EDAD:= TO_CHAR(FECHA,'YYYY')+CONT;
    END IF;
  END LOOP;
  VER('LA PRÓXIMA CELEBRACIÓN SERÁ EL DÍA '||TO_CHAR(FECHA,'DD/MM ')||EDAD||' Y SERAN '||CUMPLEAÑOS);
END;
 EXECUTE EJ4_2020('04/02/2003');
--------------------------------------------------------------------------------
--EJERCICIO 5
CREATE OR REPLACE PROCEDURE EJ5_2020(NUMERO1 NUMBER, NUMERO2 NUMBER)
AS
SUMA NUMBER :=0;
MULTIPLOS NUMBER:=0;
BEGIN
  IF NUMERO1>NUMERO2 THEN
    VER('ERROR');
  END IF;
  
  FOR CONT IN NUMERO1..NUMERO2 LOOP
    IF MOD(CONT,5)=0 THEN
      VER(CONT);
      MULTIPLOS:= MULTIPLOS+1;
      SUMA:= SUMA+CONT;
    END IF;
  END LOOP;
    VER('CUANTOS MULTIPLOS: '||MULTIPLOS);
    VER('SUMA MULTIPLOS: '||SUMA);
END;

EXECUTE EJ5_2020(2,10);













