CREATE TABLE CLIENTES
(DNI  VARCHAR2(9) PRIMARY KEY,
 NOMBRE VARCHAR2(20),
 DIRECCION VARCHAR2(30),
 TELEFONO VARCHAR2(9),
 EMAIL VARCHAR2(20)
 );
 
 CREATE TABLE PROPIETARIOS
(NIF VARCHAR2(9) PRIMARY KEY,
NUM_PROPIETARIO CHAR(5) NOT NULL,
NOMBRE VARCHAR2(20),
DIRECCION VARCHAR2(30),
AÑO_ALTA DATE DEFAULT SYSDATE,
TELEFONO VARCHAR2(9),
EMAIL VARCHAR2(20)
);

CREATE TABLE INCIDENCIAS
(COD_AVERIA CHAR(7) PRIMARY KEY,
FH_AVERIA DATE,
FH_ARREGLO DATE,
COSTE NUMBER,
MOTIVO VARCHAR2(30)
);

CREATE TABLE INMUEBLES
(REFERENCIA VARCHAR2(10) PRIMARY KEY,
TIPO CHAR,
DIRECCION VARCHAR2(10) UNIQUE NOT NULL,
NUM_HAB CHAR(2),
NUM_SERVICIOS CHAR(2),
JARDIN CHAR DEFAULT 'N',
PISCINA CHAR DEFAULT 'N',
DUEÑO VARCHAR2(9) REFERENCES PROPIETARIOS,
PRECIO_DIA NUMBER(4,2),

CONSTRAINT CK_REFERENCIA CHECK(SUBSTR(REFERENCIA,1,1) = TIPO
                              AND SUBSTR(REFERENCIA,2,1)= '-'
                              AND SUBSTR(REFERENCIA,3,8) BETWEEN 00000000 AND 99999999),
CONSTRAINT CK_TIPO CHECK(TIPO IN ('A','C')),
CONSTRAINT CK_NUM_HAB CHECK(NUM_HAB BETWEEN 00 AND 10),
CONSTRAINT CK_NUM_SERVICIOS CHECK(NUM_SERVICIOS BETWEEN 00 AND 10),
CONSTRAINT CK_JARDIN CHECK(JARDIN IN ('S','N')),
CONSTRAINT CK_PISCINA CHECK(PISCINA IN ('S','N')
));


CREATE TABLE ALQUILERES
( REFERENCIA VARCHAR2(10) REFERENCES INMUEBLES,
FECHA_ENTRADA DATE NOT NULL,
FECHA_SALIDA DATE NOT NULL,
DNI_CLI  VARCHAR2(9) REFERENCES CLIENTES,
PRECIO NUMBER NOT NULL,
NUM_FACTURA CHAR(7) NOT NULL UNIQUE,

CONSTRAINT PK_ALQUILERES PRIMARY KEY(REFERENCIA,FECHA_ENTRADA)
);

DROP TABLE ALQUILERES;
DROP TABLE INMUEBLES;
DROP TABLE INCIDENCIAS;
DROP TABLE PROPIETARIOS;
DROP TABLE CLIENTES;


ALTER TABLE CLIENTES
  ADD FECHA_ALTA DATE DEFAULT SYSDATE;
  
ALTER TABLE INMUEBLES
  DROP CONSTRAINT CK_NUM_HAB;
  