--EXAMEN 2022
--------------------------------------------------------------------------------
--EJERICIO 1
CREATE OR REPLACE PROCEDURE EXAMEN_01(NOMBRE VARCHAR2, TELEFONO VARCHAR2, FECHA DATE)
AS
EDAD NUMBER;
CONTADOR NUMBER:=0;
DIA NUMBER;
MES NUMBER;
HORA NUMBER;
MINUTOS NUMBER;
SEGUNDOS NUMBER;
BEGIN
  IF NOMBRE IS NULL OR TELEFONO IS NULL OR FECHA IS NULL THEN
    VER('ERROR, DATOS INTRODUCIDOS NULOS');
    CONTADOR:=CONTADOR+1;
  END IF;
  
  IF LENGTH(NOMBRE)<3 THEN
    VER('ERROR, NOMBRE MENOR QUE 3');
    CONTADOR:=CONTADOR+1;
  END IF;
  
  IF LENGTH(TELEFONO)!=9 THEN
    VER('ERROR, TELEFONO DÍSTINTO DE 9 DÍGITOS');
    CONTADOR:=CONTADOR+1;
  END IF;
  
  EDAD:= TRUNC((SYSDATE-FECHA)/365);
  
  IF EDAD<18 THEN
    VER('ERROR, ERES MENOR DE EDAD');
    CONTADOR:=CONTADOR+1;
  END IF;
  
  DIA:=TO_CHAR(SYSDATE,'DD');
  MES:=TO_CHAR(SYSDATE,'MM');
  HORA:=TO_CHAR(SYSDATE,'HH24');
  MINUTOS:=TO_CHAR(SYSDATE,'MI');
  SEGUNDOS:=TO_CHAR(SYSDATE,'SS');
  
  IF CONTADOR=0 THEN
    VER('TIENES UN NÚMERO PARA PARTICIPAR EN NUESTRO SORTEO: '||(DIA+MES+HORA+MINUTOS+SEGUNDOS));
  END IF;
  
END;

--------------------------------------------------------------------------------
--EJERCICIO 2
CREATE OR REPLACE PROCEDURE EXAMEN_02(NUMERO1 NUMBER, NUMERO2 NUMBER, NUMERO3 NUMBER, NUMERO4 NUMBER)
AS
POSITIVOS NUMBER:=0;
MULTIPLOS NUMBER:=0;
BEGIN
  IF NUMERO1>0 THEN
    POSITIVOS:=POSITIVOS+1;
    IF MOD(NUMERO1,5)=0 THEN 
      MULTIPLOS:=MULTIPLOS+1;
    END IF;
  END IF;
  IF NUMERO2>0 THEN
    POSITIVOS:=POSITIVOS+1;
    IF MOD(NUMERO2,5)=0 THEN 
      MULTIPLOS:=MULTIPLOS+1;
    END IF;
  END IF;
  IF NUMERO3>0 THEN
    POSITIVOS:=POSITIVOS+1;
    IF MOD(NUMERO3,5)=0 THEN 
      MULTIPLOS:=MULTIPLOS+1;
    END IF;
  END IF;
  IF NUMERO4>0 THEN
    POSITIVOS:=POSITIVOS+1;
    IF MOD(NUMERO4,5)=0 THEN 
      MULTIPLOS:=MULTIPLOS+1;
    END IF;
  END IF;
  VER('HAY '||POSITIVOS||' POSITIVOS. Y DE ESTOS '||MULTIPLOS||' SON MÚLTIPLOS DE 5.');
  IF NUMERO1=0 OR NUMERO2=0 OR NUMERO3=0 OR NUMERO4=0 THEN
    VER('NO ME GUSTAN LOS CEROS');
  END IF;
END;

--------------------------------------------------------------------------------
--EJERCICIO 3
CREATE OR REPLACE PROCEDURE EXAMEN_03(NUMERO1 NUMBER, NUMERO2 NUMBER)
AS
MENOR NUMBER;
MAYOR NUMBER;
BEGIN
  IF NUMERO1<NUMERO2 THEN
    MENOR:=NUMERO1;
    MAYOR:=NUMERO2;
  ELSE
    MENOR:=NUMERO2;
    MAYOR:=NUMERO1;
  END IF;
  
  FOR CONT IN MENOR..MAYOR LOOP
    IF MOD(CONT,10)=0 THEN
      VER(CONT);
    END IF;
  END LOOP;
END;

--------------------------------------------------------------------------------
--EJERCICIO 4
CREATE OR REPLACE PROCEDURE EXAMEN_04(NUMERO1 NUMBER, NUMERO2 NUMBER, NUMERO3 NUMBER)
AS
SUMA NUMBER;
CONTADOR NUMBER:=0;
BEGIN
  SUMA:=NUMERO1+NUMERO2;
  VER('SUMA: '||SUMA);
  IF SUMA>NUMERO3 THEN
    VER('ERROR');
  END IF;
  
  WHILE SUMA<NUMERO3 LOOP
    SUMA:=SUMA+NUMERO1+NUMERO2;
    VER('SUMA: '||SUMA);
    CONTADOR:=CONTADOR+1;
  END LOOP;
  VER('VUELTA: '||CONTADOR);
END;






















